apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata: # kpt-merge: example/du-edge-f1
  name: du-edge-f1
  namespace: oai-ran-du
  annotations:
    internal.kpt.dev/upstream-identifier: k8s.cni.cncf.io|NetworkAttachmentDefinition|example|du-edge-f1
spec:
  config: |-
    {
      "cniVersion": "0.3.1",
      "name": "du-edge-f1",
      "plugins": [
        {
          "type": "macvlan",
          "capabilities": {
            "ips": true
          },
          "master": "mltus_ens19_105",
          "mode": "bridge",
          "ipam": {
            "type": "static",
            "routes": [
              {
                "dst": "192.168.58.0/24",
                "gw": "192.168.54.1"
              }
            ]
          }
        }
      ]
    }
