apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata: # kpt-merge: example/du-edge-f1
  name: du-edge-f1
  namespace: example
  annotations:
    internal.kpt.dev/upstream-identifier: 'k8s.cni.cncf.io|NetworkAttachmentDefinition|example|du-edge-f1'
spec:
  config: "{\n  \"cniVersion\": \"0.3.1\",\n  \"name\": \"du-edge-f1\",\n  \"plugins\": [\n    {\n      \"type\": \"macvlan\",\n      \"capabilities\": {\n        \"ips\": true\n      },\n      \"master\": \"DU_F1U_MULTUSPARENTINTERFACE\",\n      \"mode\": \"bridge\",\n      \"ipam\": {\n        \"type\": \"static\",\n        \"routes\": [{ \"dst\": \"CUCP_F1C_NETWORKADDRESS\", \"gw\": \"DU_F1U_GW\" }]\n      }\n    }\n  ]\n}            "
