apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata: # kpt-merge: upf-example/upf-edge-n3
  name: upf-edge-n3
  namespace: upf-example
  annotations:
    internal.kpt.dev/upstream-identifier: 'k8s.cni.cncf.io|NetworkAttachmentDefinition|upf-example|upf-edge-n3'
spec:
  config: |
    {
      "cniVersion": "0.3.1",
      "name": "upf-core-n3",
      "plugins": [
        {
          "type": "macvlan",
          "capabilities": {
            "ips": true
          },
          "master": "UPF_N3_MULTUSPARENTINTERFACE",
          "mode": "bridge",
          "ipam": {
            "type": "static",
            "routes": [{ "dst": "CUUP_N3_NETWORKADDRESS", "gw": "UPF_N3_GW" }]
          }
        }
      ]
    }
---
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata: # kpt-merge: upf-example/upf-edge-n4
  name: upf-edge-n4
  namespace: upf-example
  annotations:
    internal.kpt.dev/upstream-identifier: 'k8s.cni.cncf.io|NetworkAttachmentDefinition|upf-example|upf-edge-n4'
spec:
  config: |
    {
      "cniVersion": "0.3.1",
      "name": "upf-core-n4",
      "plugins": [
        {
          "type": "macvlan",
          "capabilities": {
            "ips": true
          },
          "master": "UPF_N4_MULTUSPARENTINTERFACE",
          "mode": "bridge",
          "ipam": {
            "type": "static",
            "routes": [{ "dst": "SMF_N4_NETWORKADDRESS", "gw": "UPF_N4_GW" }]
          }
        }
      ]
    }
---
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata: # kpt-merge: upf-example/upf-edge-n6
  name: upf-edge-n6
  namespace: upf-example
  annotations:
    internal.kpt.dev/upstream-identifier: 'k8s.cni.cncf.io|NetworkAttachmentDefinition|upf-example|upf-edge-n6'
spec:
  config: |
    {
      "cniVersion": "0.3.1",
      "name": "upf-core-n6",
      "plugins": [
        {
          "type": "macvlan",
          "capabilities": {
            "ips": true
          },
          "master": "UPF_N6_MULTUSPARENTINTERFACE",
          "mode": "bridge",
          "ipam": {
            "type": "static"
          }
        }
      ]
    }
