apiVersion: workload.nephio.org/v1alpha1
kind: NFDeployment
metadata: # kpt-merge: upf-example/upf-example
  name: upf-edge
  namespace: oai-core
  annotations:
    internal.kpt.dev/upstream-identifier: workload.nephio.org|NFDeployment|upf-example|upf-example
spec:
  provider: upf.openairinterface.org
  capacity:
    maxDownlinkThroughput: 5G
    maxUplinkThroughput: 5G
  parametersRefs:
  - name: oai-upf-config
    apiVersion: workload.nephio.org/v1alpha1
    kind: NFConfig
  interfaces:
  - name: n3
    ipv4:
      address: 192.168.50.2/24
      gateway: 192.168.50.1
    vlanID: 30
  - name: n4
    ipv4:
      address: 192.168.51.2/24
      gateway: 192.168.51.1
    vlanID: 31
  - name: n6
    ipv4:
      address: 192.168.52.2/24
      gateway: 192.168.52.1
    vlanID: 422
  networkInstances:
  - name: vpc-internal
    interfaces:
    - n4
  - name: vpc-internet
    interfaces:
    - n6
  - name: vpc-ran
    interfaces:
    - n3
