apiVersion: v1
kind: ConfigMap
metadata: # kpt-merge: frr-k8s-system/frr-init-conf
  name: frr-init-conf
  namespace: frr-k8s-system
  annotations:
    internal.kpt.dev/upstream-identifier: '|ConfigMap|frr-k8s-system|frr-init-conf'
data: |
  sleep 20
  ip link add dev n3vrf type vrf table 1
  ip link add dev n4vrf type vrf table 2
  ip link add dev n6vrf type vrf table 3
  ip link add dev e1vrf type vrf table 4
  ip link add dev f1vrf type vrf table 5
  ip link set dev n3vrf up
  ip link set dev n4vrf up
  ip link set dev n6vrf up
  ip link set dev e1vrf up
  ip link set dev f1vrf up
  ip link set dev n3 master n3vrf
  ip link set dev n4 master n4vrf
  ip link set dev n6 master n6vrf
  ip link set dev e1 master e1vrf
  ip link set dev f1 master f1vrf
