apiVersion: v1
kind: ConfigMap
metadata: # kpt-merge: frr-k8s-system/vpp-startup-conf
  name: vpp-startup-conf
  namespace: frr-k8s-system
  annotations:
    internal.kpt.dev/upstream-identifier: '|ConfigMap|frr-k8s-system|vpp-startup-conf'
data:
  startup.conf: |
    unix {
      nodaemon
      log /var/log/vpp/vpp.log
      cli-listen /run/vpp/cli.sock
      gid vpp
      poll-sleep-usec 1000
      exec /etc/vpp/bootstrap.vpp
    }

    api-trace { on }
    api-segment { gid vpp }
    socksvr { default }

    memory {
      main-heap-size 512M
      main-heap-page-size default-hugepage
    }

    buffers {
      buffers-per-numa 128000
      default data-size 2048
      page-size default-hugepage
    }

    statseg {
      size 1G
      page-size default-hugepage
      per-node-counters off
    }

    plugins {
      plugin linux_nl_plugin.so { enable }
      plugin linux_cp_plugin.so { enable }
      plugin dpdk_plugin.so { enable }
    }

    logging {
      default-log-level info
      default-syslog-log-level notice
      class linux-cp { rate-limit 10000 level debug syslog-level debug }
      class linux-nl { rate-limit 10000 level debug syslog-level debug }
    }

    dpdk {
     dev 0000:00:14.0 {name dpdk0}
    }
---
apiVersion: v1
kind: ConfigMap
metadata: # kpt-merge: frr-k8s-system/vpp-init-conf
  name: vpp-init-conf
  namespace: frr-k8s-system
  annotations:
    internal.kpt.dev/upstream-identifier: '|ConfigMap|frr-k8s-system|vpp-init-conf'
data:
  bootstrap.vpp: "lcp lcp-sync on\nlcp lcp-auto-subint on\nip table add 1\nip table add 2\nip table add 3\nip table add 4\nip table add 5               \ncreate sub-interfaces dpdk0 101\ncreate sub-interfaces dpdk0 102\ncreate sub-interfaces dpdk0 103\ncreate sub-interfaces dpdk0 104\ncreate sub-interfaces dpdk0 105\ncreate sub-interfaces dpdk0 200\ncreate sub-interfaces dpdk0 201\ncreate sub-interfaces dpdk0 202\nset interface ip table dpdk0.101 1\nset interface ip table dpdk0.102 2\nset interface ip table dpdk0.200 2\nset interface ip table dpdk0.103 3\nset interface ip table dpdk0.104 4\nset interface ip table dpdk0.201 4\nset interface ip table dpdk0.105 5\nset interface ip table dpdk0.202 5\nset interface state dpdk0 up\nset interface state dpdk0.101 up\nset interface state dpdk0.102 up\nset interface state dpdk0.103 up\nset interface state dpdk0.104 up\nset interface state dpdk0.105 up\nset interface state dpdk0.200 up\nset interface state dpdk0.201 up\nset interface state dpdk0.202 up\nlcp create dpdk0 host-if dpdk0\nlcp create dpdk0.101 host-if n3\nlcp create dpdk0.102 host-if n4\nlcp create dpdk0.103 host-if n6\nlcp create dpdk0.104 host-if e1\nlcp create dpdk0.105 host-if f1\nlcp create dpdk0.200 host-if n4uplink\nlcp create dpdk0.201 host-if e1uplink\nlcp create dpdk0.202 host-if f1uplink\nset interface ip address dpdk0.101 192.168.50.1/24\nset interface ip address dpdk0.102 192.168.51.1/24\nset interface ip address dpdk0.103 192.168.52.1/24\nset interface ip address dpdk0.104 192.168.53.1/24\nset interface ip address dpdk0.105 192.168.54.1/24\nset interface ip address dpdk0.200 192.168.60.1/30\nset interface ip address dpdk0.201 192.168.60.5/30\nset interface ip address dpdk0.202 192.168.60.9/30\n"
